const encode = (value: string | number) => encodeURIComponent(String(value));

export const routes = {
  home: "/",
  search: "/search",
  postAd: "/post-ad",
  login: "/login",
  register: "/register",
  account: "/account",
  admin: "/admin",
  forbidden: "/forbidden",
  listing: (slug: string) => `/listing/${encode(slug)}`,
  api: {
    csrfCookie: "/sanctum/csrf-cookie",
    auth: {
      login: "/api/v1/auth/login",
      logout: "/api/v1/auth/logout",
      register: "/api/v1/auth/register",
      session: "/api/v1/auth/session",
      profile: "/api/v1/auth/profile",
      changePassword: "/api/v1/auth/change-password",
      forgotPassword: "/api/v1/auth/forgot-password",
      resetPassword: "/api/v1/auth/reset-password",
      resendVerification: "/api/v1/auth/email/verification-notification",
      email: "/api/v1/auth/email",
      phone: "/api/v1/auth/phone",
      deletion: "/api/v1/auth/deletion",
      twoFactor: "/api/v1/auth/2fa",
      recoveryEmail: "/api/v1/auth/recovery-email",
      recoveryEmailVerification: "/api/v1/auth/recovery-email/verification-notification",
      sessions: "/api/v1/auth/sessions",
      otherSessions: "/api/v1/auth/sessions/others",
      sessionItem: (id: string | number) => `/api/v1/auth/sessions/${encode(id)}`,
    },
    categories: "/api/v1/categories",
    categoryRoots: "/api/v1/category-roots",
    categoryChildren: (category: string | number) =>
      `/api/v1/categories/${encode(category)}/children`,
    categoryDetails: (category: string | number) =>
      `/api/v1/categories/${encode(category)}`,
    categoryBreadcrumbs: (category: string | number) =>
      `/api/v1/categories/${encode(category)}/breadcrumbs`,
     categoryFormSchema: (category: string | number) =>
       `/api/v1/categories/${encode(category)}/form-schema`,
     categoryFilters: (category: string | number) =>
       `/api/v1/categories/${encode(category)}/filters`,
    listings: "/api/v1/listings",
      listing: (id: string | number) => `/api/v1/listings/${encode(id)}`,
      listingHistory: (id: string | number) => `/api/v1/listings/${encode(id)}/history`,
     listingSubmit: (id: string | number) => `/api/v1/listings/${encode(id)}/submit`,
     listingPause: (id: string | number) => `/api/v1/listings/${encode(id)}/pause`,
     listingResume: (id: string | number) => `/api/v1/listings/${encode(id)}/resume`,
     listingSold: (id: string | number) => `/api/v1/listings/${encode(id)}/mark-sold`,
     listingArchive: (id: string | number) => `/api/v1/listings/${encode(id)}/archive`,
     listingRestore: (id: string | number) => `/api/v1/listings/${encode(id)}/restore`,
     listingMedia: (id: string | number) => `/api/v1/listings/${encode(id)}/media`,
     listingMediaItem: (listing: string | number, media: string | number) => `/api/v1/listings/${encode(listing)}/media/${encode(media)}`,
     listingMediaCover: (listing: string | number, media: string | number) => `/api/v1/listings/${encode(listing)}/media/${encode(media)}/cover`,
     listingMediaReorder: (id: string | number) => `/api/v1/listings/${encode(id)}/media/reorder`,
     listingFavorite: (id: string | number) => `/api/v1/listings/${encode(id)}/favorite`,
     listingView: (id: string | number) => `/api/v1/listings/${encode(id)}/view`,
     listingPhoneReveal: (id: string | number) => `/api/v1/listings/${encode(id)}/phone-reveal`,
     listingContactEvents: (id: string | number) => `/api/v1/listings/${encode(id)}/contact-events`,
      listingConversation: (id: string | number) => `/api/v1/listings/${encode(id)}/conversations`,
      conversations: "/api/v1/conversations",
      unreadConversations: "/api/v1/conversations/unread",
      conversationMessages: (id: string | number) => `/api/v1/conversations/${encode(id)}/messages`,
      conversationRead: (id: string | number) => `/api/v1/conversations/${encode(id)}/read`,
      conversationMute: (id: string | number) => `/api/v1/conversations/${encode(id)}/mute`,
      conversationLeave: (id: string | number) => `/api/v1/conversations/${encode(id)}/leave`,
      conversationReport: (id: string | number) => `/api/v1/conversations/${encode(id)}/report`,
      userBlock: (id: string | number) => `/api/v1/users/${encode(id)}/block`,
      blockedUsers: "/api/v1/me/blocked-users",
    listingBySlug: (slug: string) => `/api/v1/listings/by-slug/${encode(slug)}`,
      myListings: "/api/v1/me/listings",
      myDashboard: "/api/v1/me/dashboard",
      myFavorites: "/api/v1/me/favorites",
      reportReasons: "/api/v1/report-reasons",
      reports: "/api/v1/reports",
      notifications: "/api/v1/notifications",
      notificationsReadAll: "/api/v1/notifications/read-all",
      notificationRead: (id: string) => `/api/v1/notifications/${encode(id)}/read`,
      notificationPreferences: "/api/v1/notification-preferences",
     notificationPreference: (type: string) => `/api/v1/notification-preferences/${encode(type)}`,
      page: (slug: string) => `/api/v1/pages/${encode(slug)}`,
      pageNavigation: (location: string) => `/api/v1/pages/navigation?location=${encode(location)}`,
      banners: (placement?: string) => `/api/v1/banners${placement ? `?placement=${encode(placement)}` : ""}`,
      memberships: "/api/v1/memberships",
      myMemberships: "/api/v1/me/memberships",
      myMembershipInvitations: "/api/v1/me/membership-invitations",
      membership: (id: string | number) => `/api/v1/memberships/${encode(id)}`,
      membershipRole: (id: string | number) => `/api/v1/memberships/${encode(id)}/role`,
      membershipSuspend: (id: string | number) => `/api/v1/memberships/${encode(id)}/suspend`,
      membershipResend: (id: string | number) => `/api/v1/memberships/${encode(id)}/resend`,
       membershipCancel: (id: string | number) => `/api/v1/memberships/${encode(id)}/cancel`,
       applicationProfile: "/api/v1/me/application-profile",
       applicationProfileResume: "/api/v1/me/application-profile/resume",
       jobApply: (listing: string | number) => `/api/v1/jobs/${encode(listing)}/applications`,
      jobListingApplications: (listing: string | number) => `/api/v1/jobs/${encode(listing)}/applications`,
       myJobApplications: "/api/v1/me/job-applications",
       employerJobApplications: "/api/v1/job-applications",
      jobApplication: (id: string | number) => `/api/v1/job-applications/${encode(id)}`,
      jobApplicationStatus: (id: string | number) => `/api/v1/job-applications/${encode(id)}/status`,
      jobApplicationResume: (id: string | number) => `/api/v1/job-applications/${encode(id)}/resume`,
    admin: {
       dashboard: "/admin/api/v1/dashboard",
        listings: "/admin/api/v1/listings",
        listing: (listing: string | number) => `/admin/api/v1/listings/${encode(listing)}`,
        listingFeature: (listing: string | number) => `/admin/api/v1/listings/${encode(listing)}/feature`,
        moderationListings: "/admin/api/v1/moderation/listings",
        moderationListing: (listing: string | number) => `/admin/api/v1/moderation/listings/${encode(listing)}`,
         moderationDecision: (listing: string | number, decision: string) => `/admin/api/v1/moderation/listings/${encode(listing)}/${encode(decision)}`,
         moderationBulkApprove: "/admin/api/v1/moderation/listings/bulk-approve",
         moderationAnalyze: "/admin/api/v1/moderation/analyze",
        moderationAiReview: (listing: string | number) => `/admin/api/v1/moderation/listings/${encode(listing)}/ai-review`,
       reports: "/admin/api/v1/reports",
       report: (id: string | number) => `/admin/api/v1/reports/${encode(id)}`,
      users: "/admin/api/v1/users",
      user: (user: string | number) => `/admin/api/v1/users/${encode(user)}`,
      userStatus: (user: string | number) =>
        `/admin/api/v1/users/${encode(user)}/status`,
      roles: "/admin/api/v1/roles",
      permissions: "/admin/api/v1/permissions",
      rolePermissions: (role: string | number) =>
        `/admin/api/v1/roles/${encode(role)}/permissions`,
      userRoles: (user: string | number) =>
        `/admin/api/v1/users/${encode(user)}/roles`,
      userRole: (user: string | number, role: string | number) =>
        `/admin/api/v1/users/${encode(user)}/roles/${encode(role)}`,
      categories: "/admin/api/v1/categories",
      category: (category: string | number) =>
        `/admin/api/v1/categories/${encode(category)}`,
      categorySchema: (category: string | number) =>
        `/admin/api/v1/categories/${encode(category)}/schema-preview`,
      categoryAttributes: (category: string | number) =>
        `/admin/api/v1/categories/${encode(category)}/attributes`,
      attributes: "/admin/api/v1/attributes",
      attribute: (attribute: string | number) =>
        `/admin/api/v1/attributes/${encode(attribute)}`,
      sections: "/admin/api/v1/sections",
      section: (section: string | number) =>
        `/admin/api/v1/sections/${encode(section)}`,
       options: "/admin/api/v1/options",
       option: (option: string | number) =>
         `/admin/api/v1/options/${encode(option)}`,
       settings: "/admin/api/v1/settings",
       pages: "/admin/api/v1/pages",
       page: (page: string | number) => `/admin/api/v1/pages/${encode(page)}`,
       banners: "/admin/api/v1/banners",
       banner: (banner: string | number) => `/admin/api/v1/banners/${encode(banner)}`,
    },
  },
} as const;
