import type { Category, Listing } from "@/domain/listings/entities";
import type { CategoryRepository, ListingFilters, ListingRepository } from "@/domain/listings/repositories";

const categories: Category[] = [
  { id: 1, slug: "vehicles", name: "Vehicles", listingCount: 3 }, { id: 2, slug: "realestate", name: "Real Estate", listingCount: 1 },
  { id: 3, slug: "electronics", name: "Electronics", listingCount: 1 }, { id: 4, slug: "shopping", name: "Shopping", listingCount: 0 },
  { id: 5, slug: "jobs", name: "Jobs", listingCount: 0 }, { id: 6, slug: "services", name: "Services & Tutoring", listingCount: 0 },
  { id: 7, slug: "pets", name: "Animals & Pets", listingCount: 0 }, { id: 8, slug: "construction", name: "Construction & Industry", listingCount: 1 },
  { id: 9, slug: "motorcycles", name: "Motorcycles", parentSlug: "vehicles", listingCount: 1 }, { id: 10, slug: "cars", name: "Cars", parentSlug: "vehicles", listingCount: 1 },
  { id: 11, slug: "apartments", name: "Apartments", parentSlug: "realestate", listingCount: 1 }, { id: 12, slug: "mobile-phones", name: "Mobile Phones", parentSlug: "electronics", listingCount: 1 },
];
const image = (url: string, alt: string) => [{ url, alt, sortOrder: 1 }];
const listings: Listing[] = [
 { id:1,slug:"2020-land-rover-range-rover-sport-phev-kabul",title:"2020 Land Rover Range Rover Sport 2.0 PHEV HSE Dynamic - 124,000 km",description:"Clean hybrid SUV with automatic transmission, 4x4 drivetrain and service history. Confirm documents and final price before payment.",price:15950000,currency:"AFN",city:"Kabul",district:"Shahr-e Naw",conditionLabel:"Second Hand",badge:"featured",isFeatured:true,status:"active",viewCount:1234,createdAt:"2026-07-01",categorySlug:"cars",categoryName:"Cars",sellerName:"Malik Demo Seller",sellerPhone:"+93 700 000 000",images:image("https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1200","Gray Range Rover Sport") },
 { id:2,slug:"3-bedroom-apartment-karte-parwan",title:"3+1 Apartment in Karte Parwan - 140 sq m, Renovated",description:"Bright renovated apartment with marble floors, balcony, parking, elevator access and secure building entrance.",price:5850000,currency:"AFN",city:"Kabul",district:"Karte Parwan",conditionLabel:"Excellent",badge:"new",isFeatured:true,status:"active",viewCount:3456,createdAt:"2026-07-04",categorySlug:"apartments",categoryName:"Apartments",sellerName:"Malik Demo Seller",sellerPhone:"+93 700 000 000",images:image("/assets/real-estate/living-room.jpg","Renovated apartment living room") },
 { id:3,slug:"iphone-16-pro-max-512gb-kabul",title:"iPhone 16 Pro Max 512GB - Deep Black, Unlocked",description:"Brand new boxed phone with warranty, Face ID, 5G, original accessories and delivery available in Kabul.",price:89900,currency:"AFN",city:"Kabul",district:"Macrorayan",conditionLabel:"New",badge:"urgent",isFeatured:false,status:"active",viewCount:4567,createdAt:"2026-07-07",categorySlug:"mobile-phones",categoryName:"Mobile Phones",sellerName:"Malik Demo Seller",sellerPhone:"+93 700 000 000",images:image("https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=1200","iPhone product") },
 { id:4,slug:"honda-cbr600rr-2023-kabul",title:"2023 Honda CBR600RR - 5,200 km, Excellent",description:"Sport bike in excellent condition with ABS, LED lights, original paint and service history.",price:385000,currency:"AFN",city:"Kabul",district:"Shahr-e Naw",conditionLabel:"Used",isFeatured:false,status:"active",viewCount:2345,createdAt:"2026-06-29",categorySlug:"motorcycles",categoryName:"Motorcycles",sellerName:"Malik Demo Seller",images:image("https://images.pexels.com/photos/16330298/pexels-photo-16330298.jpeg?cs=srgb&dl=pexels-isaac-mitchell-278678383-16330298.jpg&fm=jpg","Honda motorcycle") },
 { id:5,slug:"caterpillar-320-excavator-herat",title:"Caterpillar 320 Excavator - 2021, 4,500 Hours",description:"Ready-to-work excavator with AC cabin, hydraulic thumb, quick coupler and regular service history.",price:2850000,currency:"AFN",city:"Herat",district:"Guzara",conditionLabel:"Used",isFeatured:false,status:"active",viewCount:1234,createdAt:"2026-06-24",categorySlug:"construction",categoryName:"Construction & Industry",sellerName:"Malik Demo Seller",images:image("https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=1200","Excavator") }
];
export class InMemoryMarketplaceRepository implements ListingRepository, CategoryRepository {
 async list() { return categories; }
 async search(filters: ListingFilters) { let result = listings.filter(x => x.status === "active"); const q=filters.q?.toLowerCase(); if(q) result=result.filter(x=>`${x.title} ${x.description}`.toLowerCase().includes(q)); if(filters.category) result=result.filter(x=>x.categorySlug===filters.category || categories.find(c=>c.slug===x.categorySlug)?.parentSlug===filters.category); if(filters.city) result=result.filter(x=>x.city===filters.city); if(filters.minPrice!==undefined)result=result.filter(x=>x.price>=filters.minPrice!); if(filters.maxPrice!==undefined)result=result.filter(x=>x.price<=filters.maxPrice!); if(filters.featured!==undefined)result=result.filter(x=>x.isFeatured===filters.featured); return [...result].sort((a,b)=>filters.sort==="price_asc"?a.price-b.price:filters.sort==="price_desc"?b.price-a.price:filters.sort==="popular"?b.viewCount-a.viewCount:b.createdAt.localeCompare(a.createdAt)); }
 async findBySlug(slug:string){ return listings.find(x=>x.slug===slug && x.status==="active") ?? null; }
 async incrementViews(slug:string){ const x=listings.find(x=>x.slug===slug); if(x) x.viewCount += 1; }
}
