"use client";

import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { apiClient } from "@/shared/lib/api";
import { routes } from "@/shared/lib/routes";
import { useAuth, authErrors } from "@/features/auth/auth-provider";
import styles from "@/features/auth/auth-card.module.css";

type SecuritySection = "passwordChange" | "twoFactor" | "recoveryEmail" | "accountVerification";
type FieldErrors = Record<string, string[]>;

function FormMessage({ message, error, fields }: { message: string | null; error: string | null; fields: FieldErrors }) {
  return <>{message ? <p role="status">{message}</p> : null}{error ? <p className={styles.formError} role="alert">{error}</p> : null}{Object.entries(fields).map(([name, errors]) => <p className={styles.fieldError} role="alert" key={name}>{errors[0]}</p>)}</>;
}

async function request(path: string, method: "POST" | "PATCH" | "DELETE", body?: Record<string, unknown>) {
  await apiClient.csrfCookie();
  return apiClient.request(path, { method, ...(body ? { body } : {}) });
}

export function AccountContactForm({ kind }: { kind: "email" | "phone" }) {
  const t = useTranslations("account");
  const { user, refreshUser } = useAuth();
  const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [fields, setFields] = useState<FieldErrors>({}); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(null); setError(null); setFields({}); const form = new FormData(event.currentTarget); try { await request(kind === "email" ? routes.api.auth.email : routes.api.auth.phone, "PATCH", kind === "email" ? { email: String(form.get("email")) } : { phone_country_code: String(form.get("phone_country_code")), phone: String(form.get("phone")) }); await refreshUser(); setMessage(t("contactUpdated")); } catch (reason) { const parsed = authErrors(reason); setFields(parsed.fields); setError(Object.keys(parsed.fields).length ? null : parsed.message); } finally { setSaving(false); } }
  return <section className="settings-panel"><header><div><h1>{kind === "email" ? t("emailAddress") : t("mobilePhone")}</h1><p>{kind === "email" ? t("emailDescription") : t("phoneDescription")}</p></div></header><form className={styles.card} onSubmit={submit}><div><FormMessage message={message} error={error} fields={fields} /><label>{kind === "email" ? t("emailAddress") : t("countryCode")}<input name={kind === "email" ? "email" : "phone_country_code"} type={kind === "email" ? "email" : "tel"} defaultValue={kind === "email" ? user?.email ?? "" : user?.phone_country_code ?? "+93"} required /></label>{kind === "phone" ? <label>{t("mobilePhone")}<input name="phone" type="tel" defaultValue={user?.phone ?? ""} required /></label> : null}<button disabled={saving}>{saving ? t("saving") : t("save")}</button></div></form></section>;
}

export function AccountDeletionForm() {
  const t = useTranslations("account"); const { logout } = useAuth(); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [fields, setFields] = useState<FieldErrors>({}); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!window.confirm(t("deleteConfirm"))) return; setSaving(true); setMessage(null); setError(null); setFields({}); const form = new FormData(event.currentTarget); try { await request(routes.api.auth.deletion, "DELETE", { current_password: String(form.get("current_password")) }); await logout(); } catch (reason) { const parsed = authErrors(reason); setFields(parsed.fields); setError(Object.keys(parsed.fields).length ? null : parsed.message); } finally { setSaving(false); } }
  return <section className="settings-panel"><header><div><h1>{t("deleteAccount")}</h1><p>{t("deleteDescription")}</p></div></header><form className={styles.card} onSubmit={submit}><div><FormMessage message={message} error={error} fields={fields} /><label>{t("currentPassword")}<input name="current_password" type="password" autoComplete="current-password" required /></label><button disabled={saving}>{saving ? t("saving") : t("deleteAccount")}</button></div></form></section>;
}

export function AccountSecurityForm({ section }: { section: SecuritySection }) {
  const t = useTranslations("account"); const { user, changePassword, resendVerification } = useAuth(); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string |null>(null); const [fields, setFields] = useState<FieldErrors>({}); const [saving, setSaving] = useState(false); const title = section === "passwordChange" ? t("passwordChange") : section === "twoFactor" ? t("twoFactor") : section === "recoveryEmail" ? t("recoveryEmail") : t("accountVerification");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(null); setError(null); setFields({}); const form = new FormData(event.currentTarget); try { if (section === "passwordChange") await changePassword({ currentPassword: String(form.get("current_password")), password: String(form.get("password")), passwordConfirmation: String(form.get("password_confirmation")) }); else if (section === "twoFactor") await request(routes.api.auth.twoFactor, "PATCH", { enabled: Boolean(form.get("enabled")), current_password: String(form.get("current_password")) }); else await request(routes.api.auth.recoveryEmail, "PATCH", { email: String(form.get("email")), current_password: String(form.get("current_password")) }); setMessage(section === "passwordChange" ? t("passwordChanged") : t("saved")); event.currentTarget.reset(); } catch (reason) { const parsed = authErrors(reason); setFields(parsed.fields); setError(Object.keys(parsed.fields).length ? null : parsed.message); } finally { setSaving(false); } }
  async function verify(path: string) { setSaving(true); setError(null); try { await (path === "primary" ? resendVerification() : request(routes.api.auth.recoveryEmailVerification, "POST")); setMessage(t("verificationSent")); } catch (reason) { setError(authErrors(reason).message); } finally { setSaving(false); } }
  if (section === "accountVerification") return <section className="settings-panel"><header><div><h1>{title}</h1><p>{t("verificationDescription")}</p></div></header><div className="status-rows"><div><span><b>{t("emailAddress")}</b><small>{user?.email ?? t("emailUnavailable")}</small></span><button disabled={saving || !user?.email || user.email_verified} onClick={() => void verify("primary")}>{user?.email_verified ? t("emailVerified") : t("resendVerification")}</button></div><div><span><b>{t("recoveryEmail")}</b><small>{t("recoveryVerificationDescription")}</small></span><button disabled={saving} onClick={() => void verify("recovery")}>{t("resendVerification")}</button></div></div><FormMessage message={message} error={error} fields={fields} /></section>;
  return <section className="settings-panel"><header><div><h1>{title}</h1><p>{section === "twoFactor" ? t("twoFactorDescription") : t("recoveryDescription")}</p></div></header><form className={styles.card} onSubmit={submit}><div><FormMessage message={message} error={error} fields={fields} />{section === "twoFactor" ? <label className={styles.check}><input name="enabled" type="checkbox" /> {t("enableTwoFactor")}</label> : <label>{t("recoveryEmail")}<input name="email" type="email" required /></label>}<label>{t("currentPassword")}<input name="current_password" type="password" autoComplete="current-password" required /></label>{section === "passwordChange" ? <><label>{t("newPassword")}<input name="password" type="password" autoComplete="new-password" minLength={8} required /></label><label>{t("confirmPassword")}<input name="password_confirmation" type="password" autoComplete="new-password" minLength={8} required /></label></> : null}<button disabled={saving}>{saving ? t("saving") : t("save")}</button></div></form></section>;
}

type Session = { id: string; ip_address?: string; user_agent?: string; last_activity?: number; current?: boolean };
export function SignedInDevices() { const t = useTranslations("account"); const [sessions, setSessions] = useState<Session[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState<string | null>(null); async function load() { try { const response = await apiClient.request<{ data: { sessions: Session[] } }>(routes.api.auth.sessions); setSessions(response.data.sessions); } catch (reason) { setError(authErrors(reason).message); } finally { setLoading(false); } } useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []); async function revoke(id?: string) { setSaving(id ?? "all"); setError(null); try { await request(id ? routes.api.auth.sessionItem(id) : routes.api.auth.otherSessions, "DELETE"); if (id) setSessions((items) => items.filter((item) => item.id !== id)); else await load(); } catch (reason) { setError(authErrors(reason).message); } finally { setSaving(null); } } return <section className="settings-panel"><header><div><h1>{t("signedInDevices")}</h1><p>{t("devicesDescription")}</p></div><button disabled={Boolean(saving)} onClick={() => void revoke()}>{saving === "all" ? t("saving") : t("revokeAll")}</button></header>{loading ? <p role="status">{t("loading")}</p> : error ? <p role="alert">{error}</p> : <div className="status-rows">{sessions.map((session) => <div key={session.id}><span><b>{session.user_agent ?? t("unknownDevice")}</b><small>{[session.ip_address, session.last_activity ? new Date(session.last_activity * 1000).toLocaleString() : null].filter(Boolean).join(" · ")}</small></span>{session.current ? <small>{t("currentDevice")}</small> : <button disabled={Boolean(saving)} onClick={() => void revoke(session.id)}>{saving === session.id ? t("saving") : t("revoke")}</button>}</div>)}</div>}</section>; }
