export const adminPermissions = {
  access: "admin.access",
  analytics: "analytics.view",
  users: "users.view",
  usersUpdate: "users.update",
  usersSuspend: "users.suspend",
  usersRestore: "users.restore",
  listingsCreate: "listings.create",
  roles: "roles.view",
  rolesManage: "roles.manage",
  permissions: "permissions.view",
  userRoles: "user-roles.manage",
  currencies: "currencies.view",
  currenciesManage: "currencies.manage",
  settings: "settings.view",
  settingsManage: "settings.manage",
  categories: "categories.view",
  categoriesManage: "categories.manage",
  attributes: "attributes.view",
  attributesManage: "attributes.manage",
} as const;
